blank_issues_enabled: true
contact_links:
  - name: Check the docs
    url: https://laravel-idea.com/docs/
    about: 'This repository is for reporting bugs and proposing new features. If you need help with your first steps with Laravel Idea, check out the docs!'
  - name: Security vulnerabilities
    url: https://laravel-idea.com/
    about: If you want to report a security issue, please contact our support - support@laravel-idea.com
